# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           pretty
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Imperfect Kitchen"
description:	       "Straightforward recipes with no fluff, for everyone."
author:              "Joey Lange"

# Content settings
excerpt_separator: <!--more-->

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

# Jekyll-Compose
jekyll_compose:
  auto_open: true
  default_front_matter:
    posts:
      layout: recipe
      categories: recipes
      tags: []
      image:
      total_time: 
      active_time:
      yield:
      difficulty: Easy
      equipment:
        - First item
      ingredients:
        item: quantity
      directions:
        - First step
      notes:
        - First note
    drafts:
      layout: recipe
      categories: recipes
      tags: []
      image:
      total_time: 
      active_time:
      yield:
      difficulty: Easy
      equipment:
        - First item
      ingredients:
        item: quantity
      directions:
        - First step
      notes:
        - First note