# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'imperfect-kitchen'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-162611798-1'

menu:
- {name: 'About', folder: 'pages', file: 'about/'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link: 'https://instagram.com/_imperfect_kitchen', platform: 'Instagram', rel: 'self'}
- {icon: 'mastodon', link: 'https://file-explorers.club/@jdl', platform: 'Mastodon', rel: 'self'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share this recipe'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
